// Package oui contains the types for schema 'oui'.
package oui

import "github.com/gofrs/uuid"

// Code generated by xo. DO NOT EDIT.

// FnCreateNewRegistrar calls the stored procedure 'oui.fn_create_new_registrar(text, text, text, uuid) text' on db.
func FnCreateNewRegistrar(db XODB, i_username string, i_family_name string, i_given_name string, i_organization_id uuid.UUID) (string, error) {
	var err error

	// sql query
	const sqlstr = `SELECT oui.fn_create_new_registrar($1, $2, $3, $4)`

	// run query
	var ret string
	XOLog(sqlstr, i_username, i_family_name, i_given_name, i_organization_id)
	err = db.QueryRow(sqlstr, i_username, i_family_name, i_given_name, i_organization_id).Scan(&ret)
	if err != nil {
		return "", err
	}

	return ret, nil
}
