// Package ischema contains the types for schema 'information_schema'.
package ischema

import "github.com/knq/xo/examples/pgcatalog/pgtypes"

// GENERATED BY XO. DO NOT EDIT.

// SQLImplementationInfo represents a row from information_schema.sql_implementation_info.
type SQLImplementationInfo struct {
	Tableoid               pgtypes.Oid            // tableoid
	Cmax                   pgtypes.Cid            // cmax
	Xmax                   pgtypes.Xid            // xmax
	Cmin                   pgtypes.Cid            // cmin
	Xmin                   pgtypes.Xid            // xmin
	Ctid                   pgtypes.Tid            // ctid
	ImplementationInfoID   pgtypes.CharacterData  // implementation_info_id
	ImplementationInfoName pgtypes.CharacterData  // implementation_info_name
	IntegerValue           pgtypes.CardinalNumber // integer_value
	CharacterValue         pgtypes.CharacterData  // character_value
	Comments               pgtypes.CharacterData  // comments
}
