package postgres

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// AViewOfEverythingSome represents a row from 'public.a_view_of_everything_some'.
type AViewOfEverythingSome struct {
	ABool sql.NullBool   `json:"a_bool"` // a_bool
	AText sql.NullString `json:"a_text"` // a_text
}
