package postgres

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// AFunc1In calls the stored function 'public.a_func_1_in(integer) integer' on db.
func AFunc1In(ctx context.Context, db DB, aParam int) (int, error) {
	// call public.a_func_1_in
	const sqlstr = `SELECT * FROM public.a_func_1_in($1)`
	// run
	var r0 int
	logf(sqlstr, aParam)
	if err := db.QueryRowContext(ctx, sqlstr, aParam).Scan(&r0); err != nil {
		return 0, logerror(err)
	}
	return r0, nil
}
