DROP TABLESPACE booktest INCLUDING CONTENTS AND DATAFILES;

DROP USER booktest;

CREATE TABLESPACE booktest NOLOGGING DATAFILE '/opt/oracle/oradata/ORASID/booktest.dbf' SIZE 100M AUTOEXTEND ON;

CREATE
  USER booktest
  IDENTIFIED BY booktest
  DEFAULT TABLESPACE booktest;

GRANT
  CONNECT,
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER,
  UNLIMITED TABLESPACE,
  SELECT ANY DICTIONARY
TO booktest;
