DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE authors (
  author_id INTEGER NOT NULL IDENTITY(1,1) CONSTRAINT authors_pkey PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE INDEX authors_name_idx ON authors(name);

CREATE TABLE books (
  book_id INTEGER NOT NULL IDENTITY(1,1) CONSTRAINT books_pkey PRIMARY KEY,
  author_id INTEGER NOT NULL CONSTRAINT books_author_id_fkey FOREIGN KEY REFERENCES authors(author_id),
  isbn VARCHAR(255) NOT NULL DEFAULT '' CONSTRAINT books_isbn_key UNIQUE,
  title VARCHAR(255) NOT NULL DEFAULT '',
  year INTEGER NOT NULL DEFAULT 2000,
  available DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tags VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE INDEX books_title_idx ON books(title, year);
