// Package sqlite3 contains the types for schema ''.
package sqlite3

// GENERATED BY XO. DO NOT EDIT.

import (
	"errors"
)

// AuthPermission represents a row from 'auth_permission'.
type AuthPermission struct {
	ID            int    `json:"id"`              // id
	ContentTypeID int    `json:"content_type_id"` // content_type_id
	Codename      string `json:"codename"`        // codename
	Name          string `json:"name"`            // name

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the AuthPermission exists in the database.
func (ap *AuthPermission) Exists() bool {
	return ap._exists
}

// Deleted provides information if the AuthPermission has been deleted from the database.
func (ap *AuthPermission) Deleted() bool {
	return ap._deleted
}

// Insert inserts the AuthPermission to the database.
func (ap *AuthPermission) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if ap._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO auth_permission (` +
		`content_type_id, codename, name` +
		`) VALUES (` +
		`?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, ap.ContentTypeID, ap.Codename, ap.Name)
	res, err := db.Exec(sqlstr, ap.ContentTypeID, ap.Codename, ap.Name)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	ap.ID = int(id)
	ap._exists = true

	return nil
}

// Update updates the AuthPermission in the database.
func (ap *AuthPermission) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !ap._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if ap._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE auth_permission SET ` +
		`content_type_id = ?, codename = ?, name = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, ap.ContentTypeID, ap.Codename, ap.Name, ap.ID)
	_, err = db.Exec(sqlstr, ap.ContentTypeID, ap.Codename, ap.Name, ap.ID)
	return err
}

// Save saves the AuthPermission to the database.
func (ap *AuthPermission) Save(db XODB) error {
	if ap.Exists() {
		return ap.Update(db)
	}

	return ap.Insert(db)
}

// Delete deletes the AuthPermission from the database.
func (ap *AuthPermission) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !ap._exists {
		return nil
	}

	// if deleted, bail
	if ap._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM auth_permission WHERE id = ?`

	// run query
	XOLog(sqlstr, ap.ID)
	_, err = db.Exec(sqlstr, ap.ID)
	if err != nil {
		return err
	}

	// set deleted
	ap._deleted = true

	return nil
}

// DjangoContentType returns the DjangoContentType associated with the AuthPermission's ContentTypeID (content_type_id).
//
// Generated from foreign key 'auth_permission_content_type_id_fkey'.
func (ap *AuthPermission) DjangoContentType(db XODB) (*DjangoContentType, error) {
	return DjangoContentTypeByID(db, ap.ContentTypeID)
}

// AuthPermissionsByContentTypeID retrieves a row from 'auth_permission' as a AuthPermission.
//
// Generated from index 'auth_permission_417f1b1c'.
func AuthPermissionsByContentTypeID(db XODB, contentTypeID int) ([]*AuthPermission, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, content_type_id, codename, name ` +
		`FROM auth_permission ` +
		`WHERE content_type_id = ?`

	// run query
	XOLog(sqlstr, contentTypeID)
	q, err := db.Query(sqlstr, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AuthPermission{}
	for q.Next() {
		ap := AuthPermission{
			_exists: true,
		}

		// scan
		err = q.Scan(&ap.ID, &ap.ContentTypeID, &ap.Codename, &ap.Name)
		if err != nil {
			return nil, err
		}

		res = append(res, &ap)
	}

	return res, nil
}

// AuthPermissionByContentTypeIDCodename retrieves a row from 'auth_permission' as a AuthPermission.
//
// Generated from index 'auth_permission_content_type_id_01ab375a_uniq'.
func AuthPermissionByContentTypeIDCodename(db XODB, contentTypeID int, codename string) (*AuthPermission, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, content_type_id, codename, name ` +
		`FROM auth_permission ` +
		`WHERE content_type_id = ? AND codename = ?`

	// run query
	XOLog(sqlstr, contentTypeID, codename)
	ap := AuthPermission{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, contentTypeID, codename).Scan(&ap.ID, &ap.ContentTypeID, &ap.Codename, &ap.Name)
	if err != nil {
		return nil, err
	}

	return &ap, nil
}

// AuthPermissionByID retrieves a row from 'auth_permission' as a AuthPermission.
//
// Generated from index 'auth_permission_id_pkey'.
func AuthPermissionByID(db XODB, id int) (*AuthPermission, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, content_type_id, codename, name ` +
		`FROM auth_permission ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	ap := AuthPermission{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&ap.ID, &ap.ContentTypeID, &ap.Codename, &ap.Name)
	if err != nil {
		return nil, err
	}

	return &ap, nil
}
