DROP TABLESPACE :NAME INCLUDING CONTENTS AND DATAFILES;

DROP USER :NAME;

CREATE TABLESPACE :NAME NOLOGGING DATAFILE :'DATAFILE' SIZE 100M AUTOEXTEND ON;

CREATE
  USER :NAME
  IDENTIFIED BY :PASS
  DEFAULT TABLESPACE :NAME;

GRANT
  CONNECT,
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER,
  UNLIMITED TABLESPACE,
  SELECT ANY DICTIONARY
TO :NAME;
