package postgres

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SayHello calls the stored procedure 'public.say_hello(character varying) character varying' on db.
func SayHello(ctx context.Context, db DB, v0 string) (string, error) {
	// call public.say_hello
	const sqlstr = `SELECT public.say_hello($1)`
	// run
	var ret string
	logf(sqlstr, v0)
	if err := db.QueryRowContext(ctx, sqlstr, v0).Scan(&ret); err != nil {
		return "", logerror(err)
	}
	return ret, nil
}
