DROP TABLESPACE northwind INCLUDING CONTENTS AND DATAFILES;

DROP USER northwind;

CREATE TABLESPACE northwind NOLOGGING DATAFILE '/opt/oracle/oradata/ORASID/northwind.dbf' SIZE 100M AUTOEXTEND ON;

CREATE
  USER northwind
  IDENTIFIED BY northwind
  DEFAULT TABLESPACE northwind;

GRANT
  CONNECT,
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER,
  UNLIMITED TABLESPACE,
  SELECT ANY DICTIONARY
TO northwind;
