CREATE TABLE authors (
  author_id integer GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name nvarchar2(255) DEFAULT '' NOT NULL
);

CREATE INDEX authors_name_idx ON authors(name);

CREATE TABLE books (
  book_id integer GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  author_id integer REFERENCES authors(author_id) NOT NULL,
  isbn nvarchar2(255) DEFAULT '' UNIQUE NOT NULL,
  title nvarchar2(255) DEFAULT '' NOT NULL,
  year integer DEFAULT 2000 NOT NULL,
  available timestamp with time zone NOT NULL,
  tags nvarchar2(255) DEFAULT '' NOT NULL
);

CREATE INDEX books_title_idx ON books(title, year);
