package ischema

// Code generated by xo. DO NOT EDIT.

// ApplicableRole represents a row from 'information_schema.applicable_roles'.
type ApplicableRole struct {
	Grantee     SQLIdentifier `json:"grantee"`      // grantee
	RoleName    SQLIdentifier `json:"role_name"`    // role_name
	IsGrantable YesOrNo       `json:"is_grantable"` // is_grantable
}
