package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// CharacterSet represents a row from 'information_schema.character_sets'.
type CharacterSet struct {
	CharacterSetCatalog   sql.NullString `json:"character_set_catalog"`   // character_set_catalog
	CharacterSetSchema    sql.NullString `json:"character_set_schema"`    // character_set_schema
	CharacterSetName      sql.NullString `json:"character_set_name"`      // character_set_name
	CharacterRepertoire   sql.NullString `json:"character_repertoire"`    // character_repertoire
	FormOfUse             sql.NullString `json:"form_of_use"`             // form_of_use
	DefaultCollateCatalog sql.NullString `json:"default_collate_catalog"` // default_collate_catalog
	DefaultCollateSchema  sql.NullString `json:"default_collate_schema"`  // default_collate_schema
	DefaultCollateName    sql.NullString `json:"default_collate_name"`    // default_collate_name
}
