package ischema

// Code generated by xo. DO NOT EDIT.

// CheckConstraintRoutineUsage represents a row from 'information_schema.check_constraint_routine_usage'.
type CheckConstraintRoutineUsage struct {
	ConstraintCatalog SQLIdentifier `json:"constraint_catalog"` // constraint_catalog
	ConstraintSchema  SQLIdentifier `json:"constraint_schema"`  // constraint_schema
	ConstraintName    SQLIdentifier `json:"constraint_name"`    // constraint_name
	SpecificCatalog   SQLIdentifier `json:"specific_catalog"`   // specific_catalog
	SpecificSchema    SQLIdentifier `json:"specific_schema"`    // specific_schema
	SpecificName      SQLIdentifier `json:"specific_name"`      // specific_name
}
