package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"github.com/xo/xo/_examples/pgcatalog/pgtypes"
)

// Collation represents a row from 'information_schema.collations'.
type Collation struct {
	CollationCatalog pgtypes.SQLIdentifier `json:"collation_catalog"` // collation_catalog
	CollationSchema  pgtypes.SQLIdentifier `json:"collation_schema"`  // collation_schema
	CollationName    pgtypes.SQLIdentifier `json:"collation_name"`    // collation_name
	PadAttribute     pgtypes.CharacterData `json:"pad_attribute"`     // pad_attribute

}
