package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"github.com/xo/xo/_examples/pgcatalog/pgtypes"
)

// ColumnColumnUsage represents a row from 'information_schema.column_column_usage'.
type ColumnColumnUsage struct {
	TableCatalog    pgtypes.SQLIdentifier `json:"table_catalog"`    // table_catalog
	TableSchema     pgtypes.SQLIdentifier `json:"table_schema"`     // table_schema
	TableName       pgtypes.SQLIdentifier `json:"table_name"`       // table_name
	ColumnName      pgtypes.SQLIdentifier `json:"column_name"`      // column_name
	DependentColumn pgtypes.SQLIdentifier `json:"dependent_column"` // dependent_column
}
