package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// DataTypePrivilege represents a row from 'information_schema.data_type_privileges'.
type DataTypePrivilege struct {
	ObjectCatalog sql.NullString `json:"object_catalog"` // object_catalog
	ObjectSchema  sql.NullString `json:"object_schema"`  // object_schema
	ObjectName    sql.NullString `json:"object_name"`    // object_name
	ObjectType    sql.NullString `json:"object_type"`    // object_type
	DtdIdentifier sql.NullString `json:"dtd_identifier"` // dtd_identifier
}
