package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// DomainConstraint represents a row from 'information_schema.domain_constraints'.
type DomainConstraint struct {
	ConstraintCatalog sql.NullString `json:"constraint_catalog"` // constraint_catalog
	ConstraintSchema  sql.NullString `json:"constraint_schema"`  // constraint_schema
	ConstraintName    sql.NullString `json:"constraint_name"`    // constraint_name
	DomainCatalog     sql.NullString `json:"domain_catalog"`     // domain_catalog
	DomainSchema      sql.NullString `json:"domain_schema"`      // domain_schema
	DomainName        sql.NullString `json:"domain_name"`        // domain_name
	IsDeferrable      sql.NullString `json:"is_deferrable"`      // is_deferrable
	InitiallyDeferred sql.NullString `json:"initially_deferred"` // initially_deferred
}
