package ischema

// Code generated by xo. DO NOT EDIT.

// EnabledRole represents a row from 'information_schema.enabled_roles'.
type EnabledRole struct {
	RoleName SQLIdentifier `json:"role_name"` // role_name
}
