package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"github.com/xo/xo/_examples/pgcatalog/pgtypes"
)

// EnabledRole represents a row from 'information_schema.enabled_roles'.
type EnabledRole struct {
	RoleName pgtypes.SQLIdentifier `json:"role_name"` // role_name

}
