package ischema

// Code generated by xo. DO NOT EDIT.

// ForeignTableOption represents a row from 'information_schema.foreign_table_options'.
type ForeignTableOption struct {
	ForeignTableCatalog SQLIdentifier `json:"foreign_table_catalog"` // foreign_table_catalog
	ForeignTableSchema  SQLIdentifier `json:"foreign_table_schema"`  // foreign_table_schema
	ForeignTableName    SQLIdentifier `json:"foreign_table_name"`    // foreign_table_name
	OptionName          SQLIdentifier `json:"option_name"`           // option_name
	OptionValue         CharacterData `json:"option_value"`          // option_value
}
