package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// ForeignDataWrapper represents a row from 'information_schema.foreign_data_wrappers'.
type ForeignDataWrapper struct {
	ForeignDataWrapperCatalog  sql.NullString `json:"foreign_data_wrapper_catalog"`  // foreign_data_wrapper_catalog
	ForeignDataWrapperName     sql.NullString `json:"foreign_data_wrapper_name"`     // foreign_data_wrapper_name
	AuthorizationIdentifier    sql.NullString `json:"authorization_identifier"`      // authorization_identifier
	LibraryName                sql.NullString `json:"library_name"`                  // library_name
	ForeignDataWrapperLanguage sql.NullString `json:"foreign_data_wrapper_language"` // foreign_data_wrapper_language
}
