package ischema

// Code generated by xo. DO NOT EDIT.

// ForeignDataWrapperOption represents a row from 'information_schema.foreign_data_wrapper_options'.
type ForeignDataWrapperOption struct {
	ForeignDataWrapperCatalog SQLIdentifier `json:"foreign_data_wrapper_catalog"` // foreign_data_wrapper_catalog
	ForeignDataWrapperName    SQLIdentifier `json:"foreign_data_wrapper_name"`    // foreign_data_wrapper_name
	OptionName                SQLIdentifier `json:"option_name"`                  // option_name
	OptionValue               CharacterData `json:"option_value"`                 // option_value
}
