package ischema

// Code generated by xo. DO NOT EDIT.

// ForeignServerOption represents a row from 'information_schema.foreign_server_options'.
type ForeignServerOption struct {
	ForeignServerCatalog SQLIdentifier `json:"foreign_server_catalog"` // foreign_server_catalog
	ForeignServerName    SQLIdentifier `json:"foreign_server_name"`    // foreign_server_name
	OptionName           SQLIdentifier `json:"option_name"`            // option_name
	OptionValue          CharacterData `json:"option_value"`           // option_value
}
