package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// ForeignServerOption represents a row from 'information_schema.foreign_server_options'.
type ForeignServerOption struct {
	ForeignServerCatalog sql.NullString `json:"foreign_server_catalog"` // foreign_server_catalog
	ForeignServerName    sql.NullString `json:"foreign_server_name"`    // foreign_server_name
	OptionName           sql.NullString `json:"option_name"`            // option_name
	OptionValue          sql.NullString `json:"option_value"`           // option_value
}
