package ischema

// Code generated by xo. DO NOT EDIT.

// ForeignDataWrapper represents a row from 'information_schema.foreign_data_wrappers'.
type ForeignDataWrapper struct {
	ForeignDataWrapperCatalog  SQLIdentifier `json:"foreign_data_wrapper_catalog"`  // foreign_data_wrapper_catalog
	ForeignDataWrapperName     SQLIdentifier `json:"foreign_data_wrapper_name"`     // foreign_data_wrapper_name
	AuthorizationIdentifier    SQLIdentifier `json:"authorization_identifier"`      // authorization_identifier
	LibraryName                CharacterData `json:"library_name"`                  // library_name
	ForeignDataWrapperLanguage CharacterData `json:"foreign_data_wrapper_language"` // foreign_data_wrapper_language
}
