package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// KeyColumnUsage represents a row from 'information_schema.key_column_usage'.
type KeyColumnUsage struct {
	ConstraintCatalog          sql.NullString `json:"constraint_catalog"`            // constraint_catalog
	ConstraintSchema           sql.NullString `json:"constraint_schema"`             // constraint_schema
	ConstraintName             sql.NullString `json:"constraint_name"`               // constraint_name
	TableCatalog               sql.NullString `json:"table_catalog"`                 // table_catalog
	TableSchema                sql.NullString `json:"table_schema"`                  // table_schema
	TableName                  sql.NullString `json:"table_name"`                    // table_name
	ColumnName                 sql.NullString `json:"column_name"`                   // column_name
	OrdinalPosition            sql.NullInt64  `json:"ordinal_position"`              // ordinal_position
	PositionInUniqueConstraint sql.NullInt64  `json:"position_in_unique_constraint"` // position_in_unique_constraint
}
