package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// PgForeignTableColumn represents a row from 'information_schema._pg_foreign_table_columns'.
type PgForeignTableColumn struct {
	Nspname       Name             `json:"nspname"`       // nspname
	Relname       Name             `json:"relname"`       // relname
	Attname       Name             `json:"attname"`       // attname
	Attfdwoptions []sql.NullString `json:"attfdwoptions"` // attfdwoptions
}
