package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// PgForeignTable represents a row from 'information_schema._pg_foreign_tables'.
type PgForeignTable struct {
	ForeignTableCatalog     sql.NullString   `json:"foreign_table_catalog"`    // foreign_table_catalog
	ForeignTableSchema      sql.NullString   `json:"foreign_table_schema"`     // foreign_table_schema
	ForeignTableName        sql.NullString   `json:"foreign_table_name"`       // foreign_table_name
	Ftoptions               []sql.NullString `json:"ftoptions"`                // ftoptions
	ForeignServerCatalog    sql.NullString   `json:"foreign_server_catalog"`   // foreign_server_catalog
	ForeignServerName       sql.NullString   `json:"foreign_server_name"`      // foreign_server_name
	AuthorizationIdentifier sql.NullString   `json:"authorization_identifier"` // authorization_identifier
}
