package ischema

// Code generated by xo. DO NOT EDIT.

// ReferentialConstraint represents a row from 'information_schema.referential_constraints'.
type ReferentialConstraint struct {
	ConstraintCatalog       SQLIdentifier `json:"constraint_catalog"`        // constraint_catalog
	ConstraintSchema        SQLIdentifier `json:"constraint_schema"`         // constraint_schema
	ConstraintName          SQLIdentifier `json:"constraint_name"`           // constraint_name
	UniqueConstraintCatalog SQLIdentifier `json:"unique_constraint_catalog"` // unique_constraint_catalog
	UniqueConstraintSchema  SQLIdentifier `json:"unique_constraint_schema"`  // unique_constraint_schema
	UniqueConstraintName    SQLIdentifier `json:"unique_constraint_name"`    // unique_constraint_name
	MatchOption             CharacterData `json:"match_option"`              // match_option
	UpdateRule              CharacterData `json:"update_rule"`               // update_rule
	DeleteRule              CharacterData `json:"delete_rule"`               // delete_rule
}
