package ischema

// Code generated by xo. DO NOT EDIT.

// Schematum represents a row from 'information_schema.schemata'.
type Schematum struct {
	CatalogName                SQLIdentifier `json:"catalog_name"`                  // catalog_name
	SchemaName                 SQLIdentifier `json:"schema_name"`                   // schema_name
	SchemaOwner                SQLIdentifier `json:"schema_owner"`                  // schema_owner
	DefaultCharacterSetCatalog SQLIdentifier `json:"default_character_set_catalog"` // default_character_set_catalog
	DefaultCharacterSetSchema  SQLIdentifier `json:"default_character_set_schema"`  // default_character_set_schema
	DefaultCharacterSetName    SQLIdentifier `json:"default_character_set_name"`    // default_character_set_name
	SQLPath                    CharacterData `json:"sql_path"`                      // sql_path
}
