package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// SQLFeature represents a row from 'information_schema.sql_features'.
type SQLFeature struct {
	Tableoid       Oid            `json:"tableoid"`         // tableoid
	Cmax           Cid            `json:"cmax"`             // cmax
	Xmax           Xid            `json:"xmax"`             // xmax
	Cmin           Cid            `json:"cmin"`             // cmin
	Xmin           Xid            `json:"xmin"`             // xmin
	Ctid           Tid            `json:"ctid"`             // ctid
	FeatureID      sql.NullString `json:"feature_id"`       // feature_id
	FeatureName    sql.NullString `json:"feature_name"`     // feature_name
	SubFeatureID   sql.NullString `json:"sub_feature_id"`   // sub_feature_id
	SubFeatureName sql.NullString `json:"sub_feature_name"` // sub_feature_name
	IsSupported    sql.NullString `json:"is_supported"`     // is_supported
	IsVerifiedBy   sql.NullString `json:"is_verified_by"`   // is_verified_by
	Comments       sql.NullString `json:"comments"`         // comments
}
