package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// SQLImplementationInfo represents a row from 'information_schema.sql_implementation_info'.
type SQLImplementationInfo struct {
	Tableoid               Oid            `json:"tableoid"`                 // tableoid
	Cmax                   Cid            `json:"cmax"`                     // cmax
	Xmax                   Xid            `json:"xmax"`                     // xmax
	Cmin                   Cid            `json:"cmin"`                     // cmin
	Xmin                   Xid            `json:"xmin"`                     // xmin
	Ctid                   Tid            `json:"ctid"`                     // ctid
	ImplementationInfoID   sql.NullString `json:"implementation_info_id"`   // implementation_info_id
	ImplementationInfoName sql.NullString `json:"implementation_info_name"` // implementation_info_name
	IntegerValue           sql.NullInt64  `json:"integer_value"`            // integer_value
	CharacterValue         sql.NullString `json:"character_value"`          // character_value
	Comments               sql.NullString `json:"comments"`                 // comments
}
