package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// TableConstraint represents a row from 'information_schema.table_constraints'.
type TableConstraint struct {
	ConstraintCatalog sql.NullString `json:"constraint_catalog"` // constraint_catalog
	ConstraintSchema  sql.NullString `json:"constraint_schema"`  // constraint_schema
	ConstraintName    sql.NullString `json:"constraint_name"`    // constraint_name
	TableCatalog      sql.NullString `json:"table_catalog"`      // table_catalog
	TableSchema       sql.NullString `json:"table_schema"`       // table_schema
	TableName         sql.NullString `json:"table_name"`         // table_name
	ConstraintType    sql.NullString `json:"constraint_type"`    // constraint_type
	IsDeferrable      sql.NullString `json:"is_deferrable"`      // is_deferrable
	InitiallyDeferred sql.NullString `json:"initially_deferred"` // initially_deferred
	Enforced          sql.NullString `json:"enforced"`           // enforced
}
