package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Transform represents a row from 'information_schema.transforms'.
type Transform struct {
	UdtCatalog      sql.NullString `json:"udt_catalog"`      // udt_catalog
	UdtSchema       sql.NullString `json:"udt_schema"`       // udt_schema
	UdtName         sql.NullString `json:"udt_name"`         // udt_name
	SpecificCatalog sql.NullString `json:"specific_catalog"` // specific_catalog
	SpecificSchema  sql.NullString `json:"specific_schema"`  // specific_schema
	SpecificName    sql.NullString `json:"specific_name"`    // specific_name
	GroupName       sql.NullString `json:"group_name"`       // group_name
	TransformType   sql.NullString `json:"transform_type"`   // transform_type
}
