package ischema

// Code generated by xo. DO NOT EDIT.

// Transform represents a row from 'information_schema.transforms'.
type Transform struct {
	UdtCatalog      SQLIdentifier `json:"udt_catalog"`      // udt_catalog
	UdtSchema       SQLIdentifier `json:"udt_schema"`       // udt_schema
	UdtName         SQLIdentifier `json:"udt_name"`         // udt_name
	SpecificCatalog SQLIdentifier `json:"specific_catalog"` // specific_catalog
	SpecificSchema  SQLIdentifier `json:"specific_schema"`  // specific_schema
	SpecificName    SQLIdentifier `json:"specific_name"`    // specific_name
	GroupName       SQLIdentifier `json:"group_name"`       // group_name
	TransformType   CharacterData `json:"transform_type"`   // transform_type
}
