package ischema

// Code generated by xo. DO NOT EDIT.

// UserDefinedType represents a row from 'information_schema.user_defined_types'.
type UserDefinedType struct {
	UserDefinedTypeCatalog  SQLIdentifier  `json:"user_defined_type_catalog"`  // user_defined_type_catalog
	UserDefinedTypeSchema   SQLIdentifier  `json:"user_defined_type_schema"`   // user_defined_type_schema
	UserDefinedTypeName     SQLIdentifier  `json:"user_defined_type_name"`     // user_defined_type_name
	UserDefinedTypeCategory CharacterData  `json:"user_defined_type_category"` // user_defined_type_category
	IsInstantiable          YesOrNo        `json:"is_instantiable"`            // is_instantiable
	IsFinal                 YesOrNo        `json:"is_final"`                   // is_final
	OrderingForm            CharacterData  `json:"ordering_form"`              // ordering_form
	OrderingCategory        CharacterData  `json:"ordering_category"`          // ordering_category
	OrderingRoutineCatalog  SQLIdentifier  `json:"ordering_routine_catalog"`   // ordering_routine_catalog
	OrderingRoutineSchema   SQLIdentifier  `json:"ordering_routine_schema"`    // ordering_routine_schema
	OrderingRoutineName     SQLIdentifier  `json:"ordering_routine_name"`      // ordering_routine_name
	ReferenceType           CharacterData  `json:"reference_type"`             // reference_type
	DataType                CharacterData  `json:"data_type"`                  // data_type
	CharacterMaximumLength  CardinalNumber `json:"character_maximum_length"`   // character_maximum_length
	CharacterOctetLength    CardinalNumber `json:"character_octet_length"`     // character_octet_length
	CharacterSetCatalog     SQLIdentifier  `json:"character_set_catalog"`      // character_set_catalog
	CharacterSetSchema      SQLIdentifier  `json:"character_set_schema"`       // character_set_schema
	CharacterSetName        SQLIdentifier  `json:"character_set_name"`         // character_set_name
	CollationCatalog        SQLIdentifier  `json:"collation_catalog"`          // collation_catalog
	CollationSchema         SQLIdentifier  `json:"collation_schema"`           // collation_schema
	CollationName           SQLIdentifier  `json:"collation_name"`             // collation_name
	NumericPrecision        CardinalNumber `json:"numeric_precision"`          // numeric_precision
	NumericPrecisionRadix   CardinalNumber `json:"numeric_precision_radix"`    // numeric_precision_radix
	NumericScale            CardinalNumber `json:"numeric_scale"`              // numeric_scale
	DatetimePrecision       CardinalNumber `json:"datetime_precision"`         // datetime_precision
	IntervalType            CharacterData  `json:"interval_type"`              // interval_type
	IntervalPrecision       CardinalNumber `json:"interval_precision"`         // interval_precision
	SourceDtdIdentifier     SQLIdentifier  `json:"source_dtd_identifier"`      // source_dtd_identifier
	RefDtdIdentifier        SQLIdentifier  `json:"ref_dtd_identifier"`         // ref_dtd_identifier
}
