package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// UserDefinedType represents a row from 'information_schema.user_defined_types'.
type UserDefinedType struct {
	UserDefinedTypeCatalog  sql.NullString `json:"user_defined_type_catalog"`  // user_defined_type_catalog
	UserDefinedTypeSchema   sql.NullString `json:"user_defined_type_schema"`   // user_defined_type_schema
	UserDefinedTypeName     sql.NullString `json:"user_defined_type_name"`     // user_defined_type_name
	UserDefinedTypeCategory sql.NullString `json:"user_defined_type_category"` // user_defined_type_category
	IsInstantiable          sql.NullString `json:"is_instantiable"`            // is_instantiable
	IsFinal                 sql.NullString `json:"is_final"`                   // is_final
	OrderingForm            sql.NullString `json:"ordering_form"`              // ordering_form
	OrderingCategory        sql.NullString `json:"ordering_category"`          // ordering_category
	OrderingRoutineCatalog  sql.NullString `json:"ordering_routine_catalog"`   // ordering_routine_catalog
	OrderingRoutineSchema   sql.NullString `json:"ordering_routine_schema"`    // ordering_routine_schema
	OrderingRoutineName     sql.NullString `json:"ordering_routine_name"`      // ordering_routine_name
	ReferenceType           sql.NullString `json:"reference_type"`             // reference_type
	DataType                sql.NullString `json:"data_type"`                  // data_type
	CharacterMaximumLength  sql.NullInt64  `json:"character_maximum_length"`   // character_maximum_length
	CharacterOctetLength    sql.NullInt64  `json:"character_octet_length"`     // character_octet_length
	CharacterSetCatalog     sql.NullString `json:"character_set_catalog"`      // character_set_catalog
	CharacterSetSchema      sql.NullString `json:"character_set_schema"`       // character_set_schema
	CharacterSetName        sql.NullString `json:"character_set_name"`         // character_set_name
	CollationCatalog        sql.NullString `json:"collation_catalog"`          // collation_catalog
	CollationSchema         sql.NullString `json:"collation_schema"`           // collation_schema
	CollationName           sql.NullString `json:"collation_name"`             // collation_name
	NumericPrecision        sql.NullInt64  `json:"numeric_precision"`          // numeric_precision
	NumericPrecisionRadix   sql.NullInt64  `json:"numeric_precision_radix"`    // numeric_precision_radix
	NumericScale            sql.NullInt64  `json:"numeric_scale"`              // numeric_scale
	DatetimePrecision       sql.NullInt64  `json:"datetime_precision"`         // datetime_precision
	IntervalType            sql.NullString `json:"interval_type"`              // interval_type
	IntervalPrecision       sql.NullInt64  `json:"interval_precision"`         // interval_precision
	SourceDtdIdentifier     sql.NullString `json:"source_dtd_identifier"`      // source_dtd_identifier
	RefDtdIdentifier        sql.NullString `json:"ref_dtd_identifier"`         // ref_dtd_identifier
}
