package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// ViewRoutineUsage represents a row from 'information_schema.view_routine_usage'.
type ViewRoutineUsage struct {
	TableCatalog    sql.NullString `json:"table_catalog"`    // table_catalog
	TableSchema     sql.NullString `json:"table_schema"`     // table_schema
	TableName       sql.NullString `json:"table_name"`       // table_name
	SpecificCatalog sql.NullString `json:"specific_catalog"` // specific_catalog
	SpecificSchema  sql.NullString `json:"specific_schema"`  // specific_schema
	SpecificName    sql.NullString `json:"specific_name"`    // specific_name
}
