package ischema

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// ViewColumnUsage represents a row from 'information_schema.view_column_usage'.
type ViewColumnUsage struct {
	ViewCatalog  sql.NullString `json:"view_catalog"`  // view_catalog
	ViewSchema   sql.NullString `json:"view_schema"`   // view_schema
	ViewName     sql.NullString `json:"view_name"`     // view_name
	TableCatalog sql.NullString `json:"table_catalog"` // table_catalog
	TableSchema  sql.NullString `json:"table_schema"`  // table_schema
	TableName    sql.NullString `json:"table_name"`    // table_name
	ColumnName   sql.NullString `json:"column_name"`   // column_name
}
