package sqlserver

// Code generated by xo. DO NOT EDIT.

// AViewOfEverythingSome represents a row from 'a_bit_of_everything.a_view_of_everything_some'.
type AViewOfEverythingSome struct {
	ABit  bool   `json:"a_bit"`  // a_bit
	AText string `json:"a_text"` // a_text
}
