package sqlserver

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// A2In2Out calls the stored procedure 'a_bit_of_everything.a_2_in_2_out(int, int) (int, int)' on db.
func A2In2Out(ctx context.Context, db DB, paramOne, paramTwo int) (int, int, error) {
	// call a_bit_of_everything.a_2_in_2_out
	const sqlstr = `a_bit_of_everything.a_2_in_2_out`
	// run
	var returnOne int
	var returnTwo int
	logf(sqlstr, paramOne, paramTwo)
	if _, err := db.ExecContext(ctx, sqlstr, sql.Named("param_one", paramOne), sql.Named("param_two", paramTwo), sql.Named("return_one", sql.Out{Dest: &returnOne}), sql.Named("return_two", sql.Out{Dest: &returnTwo})); err != nil {
		return 0, 0, logerror(err)
	}
	return returnOne, returnTwo, nil
}
