// Package {{ .Package }} contains the types for schema '{{ schema .Schema }}'.
package {{ .Package }}

// Code generated by xo. DO NOT EDIT.

import (
	sq "github.com/elgris/sqrl"
    "github.com/jmoiron/sqlx"
)

