// Code generated by 'yaegi extract github.com/xo/xo/types'. DO NOT EDIT.

package internal

import (
	"github.com/xo/xo/types"
	"reflect"
)

func init() {
	Symbols["github.com/xo/xo/types/types"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DbKey":          reflect.ValueOf(types.DbKey),
		"DriverDbSchema": reflect.ValueOf(types.DriverDbSchema),
		"DriverKey":      reflect.ValueOf(types.DriverKey),
		"ParseType":      reflect.ValueOf(types.ParseType),
		"SchemaKey":      reflect.ValueOf(types.SchemaKey),

		// type definitions
		"ContextKey": reflect.ValueOf((*types.ContextKey)(nil)),
		"Enum":       reflect.ValueOf((*types.Enum)(nil)),
		"Field":      reflect.ValueOf((*types.Field)(nil)),
		"Flag":       reflect.ValueOf((*types.Flag)(nil)),
		"FlagSet":    reflect.ValueOf((*types.FlagSet)(nil)),
		"ForeignKey": reflect.ValueOf((*types.ForeignKey)(nil)),
		"Index":      reflect.ValueOf((*types.Index)(nil)),
		"Proc":       reflect.ValueOf((*types.Proc)(nil)),
		"Query":      reflect.ValueOf((*types.Query)(nil)),
		"Schema":     reflect.ValueOf((*types.Schema)(nil)),
		"Table":      reflect.ValueOf((*types.Table)(nil)),
		"Type":       reflect.ValueOf((*types.Type)(nil)),
		"XO":         reflect.ValueOf((*types.XO)(nil)),
	}
}
