// Code generated by 'yaegi extract github.com/xo/xo/templates/createdbtpl'. DO NOT EDIT.

package internal

import (
	"github.com/xo/xo/templates/createdbtpl"
	"reflect"
)

func init() {
	Symbols["github.com/xo/xo/templates/createdbtpl/createdbtpl"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Constraint":     reflect.ValueOf(createdbtpl.Constraint),
		"ConstraintKey":  reflect.ValueOf(createdbtpl.ConstraintKey),
		"Engine":         reflect.ValueOf(createdbtpl.Engine),
		"EngineKey":      reflect.ValueOf(createdbtpl.EngineKey),
		"EnumMap":        reflect.ValueOf(createdbtpl.EnumMap),
		"EnumMapKey":     reflect.ValueOf(createdbtpl.EnumMapKey),
		"Esc":            reflect.ValueOf(createdbtpl.Esc),
		"EscKey":         reflect.ValueOf(createdbtpl.EscKey),
		"Files":          reflect.ValueOf(&createdbtpl.Files).Elem(),
		"Fmt":            reflect.ValueOf(createdbtpl.Fmt),
		"FmtKey":         reflect.ValueOf(createdbtpl.FmtKey),
		"FmtOpts":        reflect.ValueOf(createdbtpl.FmtOpts),
		"FmtOptsKey":     reflect.ValueOf(createdbtpl.FmtOptsKey),
		"Lang":           reflect.ValueOf(createdbtpl.Lang),
		"TrimComment":    reflect.ValueOf(createdbtpl.TrimComment),
		"TrimCommentKey": reflect.ValueOf(createdbtpl.TrimCommentKey),
	}
}
