// Code generated by 'yaegi extract github.com/xo/xo/templates/dottpl'. DO NOT EDIT.

package internal

import (
	"github.com/xo/xo/templates/dottpl"
	"reflect"
)

func init() {
	Symbols["github.com/xo/xo/templates/dottpl/dottpl"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bold":         reflect.ValueOf(dottpl.Bold),
		"BoldKey":      reflect.ValueOf(dottpl.BoldKey),
		"Color":        reflect.ValueOf(dottpl.Color),
		"ColorKey":     reflect.ValueOf(dottpl.ColorKey),
		"Defaults":     reflect.ValueOf(dottpl.Defaults),
		"DefaultsKey":  reflect.ValueOf(dottpl.DefaultsKey),
		"Direction":    reflect.ValueOf(dottpl.Direction),
		"DirectionKey": reflect.ValueOf(dottpl.DirectionKey),
		"Files":        reflect.ValueOf(&dottpl.Files).Elem(),
		"Row":          reflect.ValueOf(dottpl.Row),
		"RowKey":       reflect.ValueOf(dottpl.RowKey),
	}
}
