// Code generated by 'yaegi extract golang.org/x/tools/imports'. DO NOT EDIT.

package internal

import (
	"golang.org/x/tools/imports"
	"reflect"
)

func init() {
	Symbols["golang.org/x/tools/imports/imports"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Debug":          reflect.ValueOf(&imports.Debug).Elem(),
		"LocalPrefix":    reflect.ValueOf(&imports.LocalPrefix).Elem(),
		"Process":        reflect.ValueOf(imports.Process),
		"VendorlessPath": reflect.ValueOf(imports.VendorlessPath),

		// type definitions
		"Options": reflect.ValueOf((*imports.Options)(nil)),
	}
}
