// Code generated by 'yaegi extract mvdan.cc/gofumpt/format'. DO NOT EDIT.

package internal

import (
	"mvdan.cc/gofumpt/format"
	"reflect"
)

func init() {
	Symbols["mvdan.cc/gofumpt/format/format"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"File":   reflect.ValueOf(format.File),
		"Source": reflect.ValueOf(format.Source),

		// type definitions
		"Options": reflect.ValueOf((*format.Options)(nil)),
	}
}
