package oracle

// Code generated by xo. DO NOT EDIT.

// AViewOfEverythingSome represents a row from 'a_bit_of_everything.a_view_of_everything_some'.
type AViewOfEverythingSome struct {
	ABool  bool   `json:"a_bool"`  // a_bool
	ANclob string `json:"a_nclob"` // a_nclob
}
