package oracle

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// AFunc2In calls the stored function 'a_bit_of_everything.a_func_2_in(number, number) number' on db.
func AFunc2In(ctx context.Context, db DB, paramOne, paramTwo int64) (int64, error) {
	// call a_bit_of_everything.a_func_2_in
	const sqlstr = `SELECT a_bit_of_everything.a_func_2_in(:1, :2) FROM dual`
	// run
	var r0 int64
	logf(sqlstr, paramOne, paramTwo)
	if err := db.QueryRowContext(ctx, sqlstr, paramOne, paramTwo).Scan(&r0); err != nil {
		return 0, logerror(err)
	}
	return r0, nil
}
