package oracle

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// A1In0Out calls the stored procedure 'a_bit_of_everything.a_1_in_0_out(number)' on db.
func A1In0Out(ctx context.Context, db DB, aParam int64) error {
	// call a_bit_of_everything.a_1_in_0_out
	const sqlstr = `BEGIN a_1_in_0_out(:a_param); END;`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, sql.Named("a_param", aParam)); err != nil {
		return logerror(err)
	}
	return nil
}
