package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Enum is a enum.
type Enum struct {
	TableName string `json:"table_name"` // table_name
	EnumName  string `json:"enum_name"`  // enum_name
}

// PostgresEnums runs a custom query, returning results as Enum.
func PostgresEnums(ctx context.Context, db DB, schema string) ([]*Enum, error) {
	// query
	const sqlstr = `SELECT ` +
		`c.relname AS table_name, t.typname ` + // ::varchar AS enum_name
		`FROM pg_class c, pg_type t ` +
		`JOIN ONLY pg_namespace n ON n.oid = t.typnamespace ` +
		`JOIN ONLY pg_enum e ON t.oid = e.enumtypid ` +
		`WHERE n.nspname = $1`
	// run
	logf(sqlstr, schema)
	rows, err := db.QueryContext(ctx, sqlstr, schema)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*Enum
	for rows.Next() {
		var e Enum
		// scan
		if err := rows.Scan(&e.TableName, &e.EnumName); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &e)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// MysqlEnums runs a custom query, returning results as Enum.
func MysqlEnums(ctx context.Context, db DB, schema string) ([]*Enum, error) {
	// query
	const sqlstr = `SELECT ` +
		`table_name AS table_name, column_name AS enum_name ` +
		`FROM information_schema.columns ` +
		`WHERE data_type = 'enum' ` +
		`AND table_schema = ?`
	// run
	logf(sqlstr, schema)
	rows, err := db.QueryContext(ctx, sqlstr, schema)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*Enum
	for rows.Next() {
		var e Enum
		// scan
		if err := rows.Scan(&e.TableName, &e.EnumName); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &e)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
