package mysql

// Code generated by xo. DO NOT EDIT.

// AViewOfEverythingSome represents a row from 'a_bit_of_everything.a_view_of_everything_some'.
type AViewOfEverythingSome struct {
	ABool bool   `json:"a_bool"` // a_bool
	AText string `json:"a_text"` // a_text
}
