package mysql

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"fmt"
)

// A2In2Out calls the stored procedure 'a_bit_of_everything.a_2_in_2_out(int, int) (int, int)' on db.
func A2In2Out(ctx context.Context, db DB, paramOne, paramTwo int) (int, int, error) {
	// At the moment, the Go MySQL driver does not support stored procedures
	// with out parameters
	return 0, 0, fmt.Errorf("unsupported")
}
