package mysql

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"fmt"
)

// A1In1Out calls the stored procedure 'a_bit_of_everything.a_1_in_1_out(int) int' on db.
func A1In1Out(ctx context.Context, db DB, aParam int) (int, error) {
	// At the moment, the Go MySQL driver does not support stored procedures
	// with out parameters
	return 0, fmt.Errorf("unsupported")
}
